server:
  port: 8181

mybatis-flex:
  global-config:
    print-banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework:
        web: info
        security: trace
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/matrix?characterEncoding=UTF-8&useInformationSchema=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  messages:
    basename: i18n/api,i18n/bug,i18n/case,i18n/commons,i18n/plan,i18n/project,i18n/system
matrix:
  meter:
    jwt:
      secret-key: a4a95385c5ed79118b720e6a7538c0af106905954235bb0aeb75a7ff89a05ef5
      expiration: 86400000 # a day
      refresh-expiration: 604800000 # 7 days

springdoc:
  api-docs:
    groups:
      enabled: true